export default {
  territory: 'territory.png',
  nordic:    'nordic.png',
  rusviet:   'rusviet.png',
  togawa:    'togawa.png',
  crimea:    'crimea.png',
  saxony:    'saxony.png',
  polania:   'polania.png',
  albion:    'albion.png',
  tundra:    'tundra.png',
  mountain:  'mountain.png',
  forest:    'forest.png',
  farm:      'farm.png',
  village:   'village.png',
  lake:      'lake.png',
  factory:   'factory.png',
  encounter: 'encounter.png',
  tunnel:    'tunnel.png',
};